LArOpenCV: larcv::SBCluster Class Reference
larcv::SBCluster Class Reference
#include <SBCluster.h>
Public Member Functions
SBCluster (const std::string name="SBCluster")
Default constructor: Name is used to identify a configuration parameter set via larcv::ImageClusterManager.
virtual ~SBCluster ()
Default destructor.
const std::string & Name () const
Name accessor.
void Configure (const ::fcllite::PSet &pset)
Configuration method.
void Profile (bool doit=true)
Profile flag setter.
larcv::ContourArray_t Process (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
wrapper execution method: internally executes Process function (see there for details)
size_t ProcessCount () const
Process count.
double ProcessTime () const
Process time.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
Protected Member Functions
void _Configure_ (const ::fcllite::PSet &pset)
Inherited class configuration method.
larcv::ContourArray_t _Process_ (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
Execution method: given previous algorithm's output clusters, image, and metadata to be updated, produce clusters.
Private Attributes
int _dilation_size
int _dilation_iter
int _blur_size
float _thresh
float _thresh_maxval
Detailed Description
Definition at line 10 of file SBCluster.h.
Constructor & Destructor Documentation
larcv::SBCluster::SBCluster (const std::string name = "SBCluster") inline
Default constructor: Name is used to identify a configuration parameter set via larcv::ImageClusterManager.
Definition at line 15 of file SBCluster.h.
                                                   :
       ImageClusterBase(name),
       _dilation_size ( 5 ),
       _dilation_iter ( 2 ),
       _blur_size     ( 5 ),
       _thresh        ( 1 ),
       _thresh_maxval (255)
     {}
virtual larcv::SBCluster::~SBCluster () inline virtual
Default destructor.
Definition at line 25 of file SBCluster.h.
 {}
Member Function Documentation
void larcv::SBCluster::_Configure_ (const ::fcllite::PSet & pset) protected virtual
Inherited class configuration method.
Implements larcv::ImageClusterBase.
Definition at line 9 of file SBCluster.cxx.
References _blur_size, _dilation_iter, _dilation_size, _thresh, and _thresh_maxval.
   {
     _dilation_size = pset.get<int> ("DilationSize");
     _dilation_iter = pset.get<int> ("DilationIterations");
     _blur_size     = pset.get<int> ("BlurSize");
     _thresh        = pset.get<float> ("Thresh");
     _thresh_maxval = pset.get<float> ("ThreshMaxVal");
     // _polygon_e     = pset.get<double>("PolygonEpsilon");
   }
larcv::ContourArray_t larcv::SBCluster::_Process_ (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) protected virtual
Execution method: given previous algorithm's output clusters, image, and metadata to be updated, produce clusters.
Each cluster is represented by larcv::Contour_t. The first argument is clusters created by a previous
algorithm's execution (ignore if not needed). The second argumnet is the image to be wokred on. The
third argument is meta data to interpret a returned clusters (i.e. update metadata if return clusters
do not use the same coordinate reference as provided image, else leave unchanged).
Implements larcv::ImageClusterBase.
Definition at line 23 of file SBCluster.cxx.
References _blur_size, _dilation_iter, _dilation_size, _thresh, and _thresh_maxval.
   {
     if ( clusters.size() )
       throw larbys("This algo can only be executed first in algo chain!");
     ::cv::Mat sb_img; //(s)mooth(b)inary image
     //Dilate
     auto kernel = ::cv::getStructuringElement(cv::MORPH_ELLIPSE,::cv::Size(_dilation_size,_dilation_size));
     ::cv::dilate(img,sb_img,
          kernel,::cv::Point(-1,-1),_dilation_iter);
     //Blur
     ::cv::blur(sb_img,sb_img,
            ::cv::Size(_blur_size,_blur_size));
     //Threshold
     auto t_value = ::cv::threshold(sb_img,sb_img,
                    _thresh,_thresh_maxval,CV_THRESH_BINARY); //return type is "threshold value?"
     //Contour finding
     ContourArray_t ctor_v;
     std::vector<::cv::Vec4i> cv_hierarchy_v;
     ctor_v.clear(); cv_hierarchy_v.clear();
     ::cv::findContours(sb_img,ctor_v,cv_hierarchy_v,
                CV_RETR_EXTERNAL,
                CV_CHAIN_APPROX_SIMPLE);
     //Approximate the polygon curve using Douglas-Peucker algorithm
     // ContourArray_t ctor_result_v;
     // ctor_result_v.resize(ctor_v.size());
     // for( size_t k = 0; k < ctor_v.size(); k++ )
     //   ::cv::approxPolyDP(ctor_v[k], ctor_result_v[k], _polygon_e, true); //true to close the contours
     // return ctor_result_v;
     return ctor_v;
   }
void larcv::ImageClusterBase::Configure (const ::fcllite::PSet & pset) inherited
Configuration method.
Definition at line 16 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_Configure_(), larcv::ImageClusterBase::_profile, LARCV_DEBUG, and larcv::laropencv_base::set_verbosity().
{
     LARCV_DEBUG((*this)) << "start" << std::endl;
     this->set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",(unsigned short)(this->logger().level()))));
     _profile = cfg.get<bool>("Profile",_profile);
     this->_Configure_(cfg);
     LARCV_DEBUG((*this)) << "end" << std::endl;
   }
const larcv::logger& larcv::laropencv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterManager::Configure().
     { return *_logger; }
const std::string& larcv::ImageClusterBase::Name () const inline inherited
Name accessor.
Definition at line 54 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_name.
 { return _name; };
ContourArray_t larcv::ImageClusterBase::Process (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) inherited
wrapper execution method: internally executes Process function (see there for details)
Definition at line 27 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_proc_count, larcv::ImageClusterBase::_proc_time, larcv::ImageClusterBase::_Process_(), larcv::ImageClusterBase::_profile, larcv::ImageClusterBase::_watch, larcv::Watch::Start(), and larcv::Watch::WallTime().
   {
     if(!_profile) return this->_Process_(clusters,img,meta);
     _watch.Start();
     auto result = this->_Process_(clusters,img,meta);
     _proc_time += _watch.WallTime();
     ++_proc_count;
     return result;
   }
size_t larcv::ImageClusterBase::ProcessCount () const inline inherited
Process count.
Definition at line 70 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_count.
 { return _proc_count; }
double larcv::ImageClusterBase::ProcessTime () const inline inherited
Process time.
Definition at line 72 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_time.
 { return _proc_time; }
void larcv::ImageClusterBase::Profile (bool doit = true) inline inherited
Profile flag setter.
Definition at line 60 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_profile.
 { _profile = doit; }
void larcv::laropencv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterBase::Configure(), and larcv::ImageClusterManager::Configure().
     { _logger->set(level); }
Member Data Documentation
int larcv::SBCluster::_blur_size private
Definition at line 41 of file SBCluster.h.
Referenced by _Configure_(), and _Process_().
int larcv::SBCluster::_dilation_iter private
Definition at line 40 of file SBCluster.h.
Referenced by _Configure_(), and _Process_().
int larcv::SBCluster::_dilation_size private
Definition at line 39 of file SBCluster.h.
Referenced by _Configure_(), and _Process_().
float larcv::SBCluster::_thresh private
Definition at line 42 of file SBCluster.h.
Referenced by _Configure_(), and _Process_().
float larcv::SBCluster::_thresh_maxval private
Definition at line 43 of file SBCluster.h.
Referenced by _Configure_(), and _Process_().
The documentation for this class was generated from the following files:
SBCluster.h
SBCluster.cxx