LArOpenCV: larcv::ToyImageCluster Class Reference
larcv::ToyImageCluster Class Reference
A simple clustering algorithm meant to serve for testing/example by Kazu.
#include <ToyImageCluster.h>
Public Member Functions
ToyImageCluster (const std::string name="ToyImageCluster")
Default constructor.
~ToyImageCluster ()
Default destructor.
const std::string & Name () const
Name accessor.
void Configure (const ::fcllite::PSet &pset)
Configuration method.
void Profile (bool doit=true)
Profile flag setter.
larcv::ContourArray_t Process (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
wrapper execution method: internally executes Process function (see there for details)
size_t ProcessCount () const
Process count.
double ProcessTime () const
Process time.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
Protected Member Functions
void _Configure_ (const ::fcllite::PSet &pset)
Configuration method.
larcv::ContourArray_t _Process_ (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
Process method.
Private Attributes
std::vector< double > _canny_params
Detailed Description
A simple clustering algorithm meant to serve for testing/example by Kazu.
Definition at line 24 of file ToyImageCluster.h.
Constructor & Destructor Documentation
larcv::ToyImageCluster::ToyImageCluster (const std::string name = "ToyImageCluster") inline
Default constructor.
Definition at line 29 of file ToyImageCluster.h.
                                                             : ImageClusterBase(name)
     {}
larcv::ToyImageCluster::~ToyImageCluster () inline
Default destructor.
Definition at line 33 of file ToyImageCluster.h.
 {}
Member Function Documentation
void larcv::ToyImageCluster::_Configure_ (const ::fcllite::PSet & pset) protected virtual
Configuration method.
Implements larcv::ImageClusterBase.
Definition at line 9 of file ToyImageCluster.cxx.
References _canny_params.
   {
     _canny_params = pset.get<std::vector<double> >("CannyParams");
     if(_canny_params.size() != 3) throw larbys("CannyParams must be length 3 vector!");
   }
ContourArray_t larcv::ToyImageCluster::_Process_ (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) protected virtual
Process method.
Implements larcv::ImageClusterBase.
Definition at line 15 of file ToyImageCluster.cxx.
References _canny_params.
   {
     ::cv::Mat blurred_img;
     ::cv::blur( img, blurred_img, ::cv::Size(3,3) );
     ::cv::Canny(blurred_img,blurred_img,_canny_params[0],_canny_params[1],_canny_params[2]);
     ContourArray_t result;
     std::vector<cv::Vec4i> cv_hierarchy_v;
     //::cv::findContours(_canny_v[plane],cv_contour_v,cv_hierarchy_v,CV_RETR_EXTERNAL,CV_CHAIN_APPROX_SIMPLE);
     ::cv::findContours(blurred_img,result,cv_hierarchy_v,
                CV_RETR_EXTERNAL,
                CV_CHAIN_APPROX_SIMPLE);
     //std::cout<<result.size()<<std::endl;
     return result;
   }
void larcv::ImageClusterBase::Configure (const ::fcllite::PSet & pset) inherited
Configuration method.
Definition at line 16 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_Configure_(), larcv::ImageClusterBase::_profile, LARCV_DEBUG, and larcv::laropencv_base::set_verbosity().
{
     LARCV_DEBUG((*this)) << "start" << std::endl;
     this->set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",(unsigned short)(this->logger().level()))));
     _profile = cfg.get<bool>("Profile",_profile);
     this->_Configure_(cfg);
     LARCV_DEBUG((*this)) << "end" << std::endl;
   }
const larcv::logger& larcv::laropencv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterManager::Configure().
     { return *_logger; }
const std::string& larcv::ImageClusterBase::Name () const inline inherited
Name accessor.
Definition at line 54 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_name.
 { return _name; };
ContourArray_t larcv::ImageClusterBase::Process (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) inherited
wrapper execution method: internally executes Process function (see there for details)
Definition at line 27 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_proc_count, larcv::ImageClusterBase::_proc_time, larcv::ImageClusterBase::_Process_(), larcv::ImageClusterBase::_profile, larcv::ImageClusterBase::_watch, larcv::Watch::Start(), and larcv::Watch::WallTime().
   {
     if(!_profile) return this->_Process_(clusters,img,meta);
     _watch.Start();
     auto result = this->_Process_(clusters,img,meta);
     _proc_time += _watch.WallTime();
     ++_proc_count;
     return result;
   }
size_t larcv::ImageClusterBase::ProcessCount () const inline inherited
Process count.
Definition at line 70 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_count.
 { return _proc_count; }
double larcv::ImageClusterBase::ProcessTime () const inline inherited
Process time.
Definition at line 72 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_time.
 { return _proc_time; }
void larcv::ImageClusterBase::Profile (bool doit = true) inline inherited
Profile flag setter.
Definition at line 60 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_profile.
 { _profile = doit; }
void larcv::laropencv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterBase::Configure(), and larcv::ImageClusterManager::Configure().
     { _logger->set(level); }
Member Data Documentation
std::vector<double> larcv::ToyImageCluster::_canny_params private
Definition at line 47 of file ToyImageCluster.h.
Referenced by _Configure_(), and _Process_().
The documentation for this class was generated from the following files:
ToyImageCluster.h
ToyImageCluster.cxx