LArOpenCV: larlite::LArImageWire Class Reference
larlite::LArImageWire Class Reference
User custom analysis class made by SHELL_USER_NAME.
#include <LArImageWire.h>
Public Member Functions
LArImageWire (const std::string name="LArImageWire")
Default constructor.
virtual ~LArImageWire ()
Default destructor.
bool initialize ()
IMPLEMENT in LArImageClusterBase.cc! Initialization method to be called before the analysis event loop.
bool analyze (storage_manager *storage)
IMPLEMENT in LArImageClusterBase.cc! Analyze a data event-by-event.
bool finalize ()
IMPLEMENT in LArImageClusterBase.cc! Finalize method to be called after all events processed.
larcv::ImageClusterManager & algo_manager (size_t plane_id)
const std::vector
< larcv::ImageClusterManager > & algo_manager_set () const
const std::string & producer () const
void set_config (const std::string cfg_file)
Protected Member Functions
void _Report_ () const
void _Configure_ (const ::fcllite::PSet &)
void store_clusters (storage_manager *storage)
void extract_image (storage_manager *storage)
Protected Attributes
double _charge_to_gray_scale
::larcv::ImageManager _img_mgr
Detailed Description
User custom analysis class made by SHELL_USER_NAME.
Definition at line 28 of file LArImageWire.h.
Constructor & Destructor Documentation
larlite::LArImageWire::LArImageWire (const std::string name = "LArImageWire") inline
Default constructor.
Definition at line 33 of file LArImageWire.h.
 : LArImageClusterBase(name) {}
virtual larlite::LArImageWire::~LArImageWire () inline virtual
Default destructor.
Definition at line 36 of file LArImageWire.h.
 {}
Member Function Documentation
void larlite::LArImageWire::_Configure_ (const ::fcllite::PSet & pset) protected virtual
Implements larlite::LArImageClusterBase.
Definition at line 9 of file LArImageWire.cxx.
References _charge_to_gray_scale.
   {
     _charge_to_gray_scale = pset.get<double>("Q2Gray");
   }
void larlite::LArImageWire::_Report_ () const inline protected virtual
Implements larlite::LArImageClusterBase.
Definition at line 40 of file LArImageWire.h.
 {}
larcv::ImageClusterManager & larlite::LArImageClusterBase::algo_manager (size_t plane_id) inherited
Definition at line 21 of file LArImageClusterBase.cxx.
References larlite::LArImageClusterBase::_alg_mgr_v.
   {
     if(plane_id >= _alg_mgr_v.size()) throw ::larcv::larbys("ImageClusterManager not found (invalid plane ID)!");
     return _alg_mgr_v[plane_id];
   }
const std::vector< larcv::ImageClusterManager > & larlite::LArImageClusterBase::algo_manager_set () const inherited
Definition at line 18 of file LArImageClusterBase.cxx.
References larlite::LArImageClusterBase::_alg_mgr_v.
Referenced by larlite::LArImageHit::store_clusters().
   { return _alg_mgr_v; }
bool larlite::LArImageClusterBase::analyze (storage_manager * storage) inherited
IMPLEMENT in LArImageClusterBase.cc! Analyze a data event-by-event.
Definition at line 52 of file LArImageClusterBase.cxx.
References larlite::LArImageClusterBase::_alg_mgr_v, larlite::LArImageClusterBase::_img_mgr, larlite::LArImageClusterBase::_orig_img_mgr, larlite::LArImageClusterBase::_process_count, larlite::LArImageClusterBase::_process_time_analyze, larlite::LArImageClusterBase::_process_time_cluster_storage, larlite::LArImageClusterBase::_process_time_image_extraction, larlite::LArImageClusterBase::_store_original_img, larcv::ImageManager::clear(), larlite::LArImageClusterBase::extract_image(), larcv::ImageManager::img_at(), larcv::ImageManager::meta_at(), larcv::ImageManager::push_back(), larcv::ImageManager::size(), larcv::Watch::Start(), larlite::LArImageClusterBase::store_clusters(), and larcv::Watch::WallTime().
{
     _img_mgr.clear();
     _orig_img_mgr.clear();
     ::larcv::Watch watch_all, watch_one;
     watch_all.Start();
     watch_one.Start();
     this->extract_image(storage);
     _process_time_image_extraction += watch_one.WallTime();
     if(_store_original_img) {
       for(size_t plane=0; plane<_img_mgr.size(); ++plane) {
     ::cv::Mat img;
     _img_mgr.img_at(plane).copyTo(img);
     _orig_img_mgr.push_back(img,_img_mgr.meta_at(plane));
       }
     }
     if(_img_mgr.size() != _alg_mgr_v.size()) throw ::larcv::larbys("# of imaged created != # of planes!");
     for(size_t plane = 0; plane < _alg_mgr_v.size(); ++plane) {
       auto& alg_mgr = _alg_mgr_v[plane];
       auto const& img = _img_mgr.img_at(plane);
       auto const& meta = _img_mgr.meta_at(plane);
       if(!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       alg_mgr.Process(img,meta);
     }
     watch_one.Start();
     this->store_clusters(storage);
     _process_time_cluster_storage += watch_one.WallTime();
     _process_time_analyze += watch_all.WallTime();
     ++_process_count;
     return true;
   }
void larlite::LArImageWire::extract_image (storage_manager * storage) protected virtual
Implements larlite::LArImageClusterBase.
Definition at line 23 of file LArImageWire.cxx.
References _charge_to_gray_scale, larlite::LArImageClusterBase::_img_mgr, larcv::ImageManager::img_at(), larlite::LArImageClusterBase::producer(), and larcv::ImageManager::push_back().
   {
     auto const& geom = ::larutil::Geometry::GetME();
     const size_t nplanes = geom->Nplanes();
     auto ev_wire = storage->get_data<event_wire>(producer());
     if(!ev_wire) throw DataFormatException("Could not locate Wire data product!");
     std::vector< std::pair<size_t,size_t> > wire_range_v(nplanes,std::pair<size_t,size_t>(1e12,0));
     std::vector< std::pair<size_t,size_t> > tick_range_v(nplanes,std::pair<size_t,size_t>(1e12,0));
     for(auto const& wire_data : *ev_wire) {
       auto const& wid = geom->ChannelToWireID(wire_data.Channel());
       auto& wire_range = wire_range_v[wid.Plane];
       if(wire_range.first  > wid.Wire) wire_range.first  = wid.Wire;
       if(wire_range.second < wid.Wire) wire_range.second = wid.Wire;
       auto& tick_range = tick_range_v[wid.Plane];
       auto const& roi_v = wire_data.SignalROI();
       for(auto const& roi : roi_v.get_ranges()) {
     size_t start_tick = roi.begin_index();
     size_t last_tick = start_tick + roi.size() - 1;
     if(tick_range.first  > start_tick) tick_range.first  = start_tick;
     if(tick_range.second < last_tick)  tick_range.second = last_tick;
       }
     }
     for(size_t plane=0; plane<nplanes; ++plane) {
       auto const& wire_range = wire_range_v[plane];
       auto const& tick_range = tick_range_v[plane];
       size_t nticks = tick_range.second - tick_range.first + 2;
       size_t nwires = wire_range.second - wire_range.first + 2;
       ::larcv::ImageMeta meta((double)nwires,(double)nticks,nwires,nticks,wire_range.first,tick_range.first);
       if(!nticks || !nwires)
     _img_mgr.push_back(cv::Mat(),meta);
       else
     _img_mgr.push_back(::cv::Mat(nwires, nticks, CV_8UC1, cvScalar(0.)),meta);
     }
     for(auto const& wire_data : *ev_wire) {
       auto const& wid = geom->ChannelToWireID(wire_data.Channel());
       auto& mat = _img_mgr.img_at(wid.Plane);
       auto const& roi_v = wire_data.SignalROI();
       auto const& wire_range = wire_range_v[wid.Plane];
       auto const& tick_range = tick_range_v[wid.Plane];
       for(auto const& roi : roi_v.get_ranges()) {
     size_t start_tick = roi.begin_index();
     for(size_t adc_index=0; adc_index < roi.size(); ++adc_index) {
       size_t x = wid.Wire - wire_range.first;
       size_t y = start_tick + adc_index - tick_range.first;
       double q = roi[adc_index] / _charge_to_gray_scale;
       q += (double)(mat.at<unsigned char>(x,y));
       if(q<0) q=0.;
       if(q>255) q=255;
       mat.at<unsigned char>(x,y) = (unsigned char)((int)q);
     }
       }
     }
   }
bool larlite::LArImageClusterBase::finalize () inherited
IMPLEMENT in LArImageClusterBase.cc! Finalize method to be called after all events processed.
Definition at line 113 of file LArImageClusterBase.cxx.
References larlite::LArImageClusterBase::_alg_mgr_v, and larlite::LArImageClusterBase::Report().
{
     Report();
     for(size_t plane=0; plane < _alg_mgr_v.size(); ++plane) {
       std::cout << "  \033[95mImageClusterManager\033[00m @ Plane " << plane << std::endl;
       _alg_mgr_v[plane].Report();
       std::cout << std::endl;
     }
     return true;
   }
bool larlite::LArImageClusterBase::initialize () inherited
IMPLEMENT in LArImageClusterBase.cc! Initialization method to be called before the analysis event loop.
Definition at line 27 of file LArImageClusterBase.cxx.
References larlite::LArImageClusterBase::_alg_mgr_v, larlite::LArImageClusterBase::_config_file, larlite::LArImageClusterBase::_Configure_(), larlite::LArImageClusterBase::_process_count, larlite::LArImageClusterBase::_process_time_analyze, larlite::LArImageClusterBase::_process_time_cluster_storage, larlite::LArImageClusterBase::_process_time_image_extraction, larlite::LArImageClusterBase::_producer, larlite::LArImageClusterBase::_profile, and larlite::LArImageClusterBase::_store_original_img.
{
     ::fcllite::ConfigManager cfg_mgr(_name);
     cfg_mgr.AddCfgFile(_config_file);
     auto const& main_cfg = cfg_mgr.Config().get_pset(_name);
     _profile = main_cfg.get<bool>("Profile");
     _producer = main_cfg.get<std::string>("Producer");
     _store_original_img = main_cfg.get<bool>("StoreOriginalImage");
     _process_count = 0;
     _process_time_image_extraction = 0;
     _process_time_analyze = 0;
     _process_time_cluster_storage = 0;
     this->_Configure_(main_cfg);
     if(_producer.empty()) throw ::larcv::larbys("No producer specified...");
     for(auto& mgr : _alg_mgr_v) mgr.Configure(cfg_mgr.Config().get_pset(mgr.Name()));
     return true;
   }
const std::string& larlite::LArImageClusterBase::producer () const inline inherited
Definition at line 58 of file LArImageClusterBase.h.
References larlite::LArImageClusterBase::_producer.
Referenced by extract_image(), larlite::LArImageHit::extract_image(), and larlite::LArImageHit::store_clusters().
 { return _producer; }
void larlite::LArImageClusterBase::set_config (const std::string cfg_file) inline inherited
Definition at line 60 of file LArImageClusterBase.h.
References larlite::LArImageClusterBase::_config_file.
 {_config_file=cfg_file;}
void larlite::LArImageWire::store_clusters (storage_manager * storage) protected virtual
Implements larlite::LArImageClusterBase.
Definition at line 14 of file LArImageWire.cxx.
References larcaffe::msg::kWARNING.
   {
     static bool warn_once = false;
     if(!warn_once) {
       print(msg::kWARNING,__FUNCTION__,"Cluster storage is not implemented...");
       warn_once = true;
     }
   }
Member Data Documentation
double larlite::LArImageWire::_charge_to_gray_scale protected
Definition at line 48 of file LArImageWire.h.
Referenced by _Configure_(), and extract_image().
::larcv::ImageManager larlite::LArImageClusterBase::_img_mgr protected inherited
Definition at line 79 of file LArImageClusterBase.h.
Referenced by larlite::LArImageClusterBase::analyze(), extract_image(), and larlite::LArImageHit::extract_image().
The documentation for this class was generated from the following files:
LArImageWire.h
LArImageWire.cxx