LArOpenCV: larcv::Watch Class Reference
larcv::Watch Class Reference
a very simple stopwatch class for simple time measurement
#include <Watch.h>
Public Member Functions
Watch ()
~Watch ()
void Start ()
Start stop watch.
double WallTime ()
Report wall-clock time [s] since Start() call.
double CPUTime ()
Report cpu-clock time [s] since Start() call.
Private Attributes
double _cpu_time_start
double _wall_time_start
Detailed Description
a very simple stopwatch class for simple time measurement
Definition at line 27 of file Watch.h.
Constructor & Destructor Documentation
larcv::Watch::Watch () inline
Definition at line 29 of file Watch.h.
 {}
larcv::Watch::~Watch () inline
Definition at line 30 of file Watch.h.
 {}
Member Function Documentation
double larcv::Watch::CPUTime () inline
Report cpu-clock time [s] since Start() call.
Definition at line 51 of file Watch.h.
References _cpu_time_start.
                      {
       // Get cpu time
       double now = (double)(clock());
       // Return diff
       return (now - _cpu_time_start)/CLOCKS_PER_SEC;
     }
void larcv::Watch::Start () inline
Start stop watch.
Definition at line 33 of file Watch.h.
References _cpu_time_start, and _wall_time_start.
Referenced by larlite::LArImageClusterBase::analyze(), larcv::ImageClusterManager::Process(), and larcv::ImageClusterBase::Process().
                  {
       // Get current wall time
       struct timeval current_time;
       gettimeofday(&current_time,NULL);
       _wall_time_start = (double)current_time.tv_sec + (double)current_time.tv_usec * 1.e-6;
       // Get current cpu time
       _cpu_time_start = (double)(clock());
     }
double larcv::Watch::WallTime () inline
Report wall-clock time [s] since Start() call.
Definition at line 42 of file Watch.h.
References _wall_time_start.
Referenced by larlite::LArImageClusterBase::analyze(), larcv::ImageClusterManager::Process(), and larcv::ImageClusterBase::Process().
                       {
       // Get current wall time
       struct timeval current_time;
       gettimeofday(&current_time,NULL);
       double now = (double)current_time.tv_sec + (double)current_time.tv_usec * 1.e-6;
       // Return diff
       return (now - _wall_time_start);
     }
Member Data Documentation
double larcv::Watch::_cpu_time_start private
Definition at line 58 of file Watch.h.
Referenced by CPUTime(), and Start().
double larcv::Watch::_wall_time_start private
Definition at line 59 of file Watch.h.
Referenced by Start(), and WallTime().
The documentation for this class was generated from the following file:
Watch.h