LArOpenCV: larcv::laropencv_base Class Reference
larcv::laropencv_base Class Reference
Very base class of all everything else defined in this framework.
#include <laropencv_base.h>
Public Member Functions
laropencv_base (const std::string logger_name="laropencv_base")
Default constructor.
laropencv_base (const laropencv_base &original)
Default copy constructor.
virtual ~laropencv_base ()
Default destructor.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
Private Attributes
larcv::logger * _logger
logger
Detailed Description
Very base class of all everything else defined in this framework.
Definition at line 27 of file laropencv_base.h.
Constructor & Destructor Documentation
larcv::laropencv_base::laropencv_base (const std::string logger_name = "laropencv_base") inline
Default constructor.
Definition at line 32 of file laropencv_base.h.
References _logger.
       : _logger(nullptr)
     { _logger = &(::larcv::logger::get(logger_name)); }
larcv::laropencv_base::laropencv_base (const laropencv_base & original) inline
Default copy constructor.
Definition at line 37 of file laropencv_base.h.
 : _logger(original._logger) {}
virtual larcv::laropencv_base::~laropencv_base () inline virtual
Default destructor.
Definition at line 40 of file laropencv_base.h.
 {};
Member Function Documentation
const larcv::logger& larcv::laropencv_base::logger () const inline
Logger getter.
Definition at line 43 of file laropencv_base.h.
References _logger.
Referenced by larcv::ImageClusterManager::Configure().
     { return *_logger; }
void larcv::laropencv_base::set_verbosity (::larcv::msg::Level_t level) inline
Verbosity level.
Definition at line 47 of file laropencv_base.h.
References _logger.
Referenced by larcv::ImageClusterBase::Configure(), and larcv::ImageClusterManager::Configure().
     { _logger->set(level); }
Member Data Documentation
larcv::logger* larcv::laropencv_base::_logger private
logger
Definition at line 52 of file laropencv_base.h.
Referenced by laropencv_base(), logger(), and set_verbosity().
The documentation for this class was generated from the following file:
laropencv_base.h