LArOpenCV: larcv::ImageClusterBase Class Reference
larcv::ImageClusterBase Class Reference abstract
An abstract base class for ImageCluster algorithms.
#include <ImageClusterBase.h>
Public Member Functions
ImageClusterBase (const std::string name="noname")
Default constructor: Name is used to identify a configuration parameter set via larcv::ImageClusterManager.
virtual ~ImageClusterBase ()
Default destructor.
const std::string & Name () const
Name accessor.
virtual void Configure (const ::fcllite::PSet &pset)=0
Configuration method.
larcv::ContourArray_t Process (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
wrapper execution method: internally executes Process function (see there for details)
double AverageProcessTime () const
Process time getter.
Protected Member Functions
virtual larcv::ContourArray_t _Process_ (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)=0
Execution method: given previous algorithm's output clusters, image, and metadata to be updated, produce clusters.
Private Attributes
std::string _name
name identifier, used to fetch configuration
larcv::Watch _watch
algorithm profile stopwatch
double _proc_time
algorithm execution time record (cumulative)
double _proc_count
algorithm execution counter (cumulative)
Detailed Description
An abstract base class for ImageCluster algorithms.
Its role is to construct a set of "cluster" given an image.
An algorithm instance is expected to be "configured" and "executed" via larcv::ImageClusterManager, though a user
can perform those actions by hand (which may be useful for development work) as well if wished.
larcv::ImageClusterManager executes a chain of algorithms that inherit from ImageClusterBase. Each algorithm instance
receives an image, information about previous algorithm's clustering result, and meta data to be updated for resulting
clusters from it. See larcv::ImageClusterManager for more details.
Configuration parameters are passed via fhicllite::PSet (which is constructed via larcv::ImageClusterManager)
and a derived class must implement ImageClusterBase::Configure abstruct method. An execution of an algorithm
is done inside an abstract method ImageClusterBase::Process method which must be implemented in a child class.
A cluster is represented as a 2D contour (larcv::Contour_t). The execution method recieves 3 inputs: 0) a set of
pre-defined clusters (typically a set of clusters created by the previous algorithm in a chain executed by
larcv::ImageClusterManager), 1) cv::Mat representing 2D image, and 2) larcv::ImageMeta which contains meta data
of 1) and should be updated to interpret the algorithm's return larcv::Contour_t if needed.
Definition at line 41 of file ImageClusterBase.h.
Constructor & Destructor Documentation
larcv::ImageClusterBase::ImageClusterBase (const std::string name = "noname")
Default constructor: Name is used to identify a configuration parameter set via larcv::ImageClusterManager.
Definition at line 8 of file ImageClusterBase.cxx.
     : _name(name)
     , _proc_time(0.)
     , _proc_count(0.)
   {}
virtual larcv::ImageClusterBase::~ImageClusterBase () inline virtual
Default destructor.
Definition at line 49 of file ImageClusterBase.h.
 {}
Member Function Documentation
virtual larcv::ContourArray_t larcv::ImageClusterBase::_Process_ (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) protected pure virtual
Execution method: given previous algorithm's output clusters, image, and metadata to be updated, produce clusters.
Each cluster is represented by larcv::Contour_t. The first argument is clusters created by a previous
algorithm's execution (ignore if not needed). The second argumnet is the image to be wokred on. The
third argument is meta data to interpret a returned clusters (i.e. update metadata if return clusters
do not use the same coordinate reference as provided image, else leave unchanged).
Implemented in larcv::ToyImageCluster.
Referenced by Process().
double larcv::ImageClusterBase::AverageProcessTime () const inline
Process time getter.
Definition at line 65 of file ImageClusterBase.h.
References _proc_count, and _proc_time.
 { return _proc_time / _proc_count; }
virtual void larcv::ImageClusterBase::Configure (const ::fcllite::PSet & pset) pure virtual
Configuration method.
Implemented in larcv::ToyImageCluster.
const std::string& larcv::ImageClusterBase::Name () const inline
Name accessor.
Definition at line 52 of file ImageClusterBase.h.
References _name.
 { return _name; };
ContourArray_t larcv::ImageClusterBase::Process (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta)
wrapper execution method: internally executes Process function (see there for details)
Definition at line 14 of file ImageClusterBase.cxx.
References _proc_count, _proc_time, _Process_(), _watch, larcv::Watch::Start(), and larcv::Watch::WallTime().
   {
     _watch.Start();
     auto result = this->_Process_(clusters,img,meta);
     _proc_time += _watch.WallTime();
     ++_proc_count;
     return result;
   }
Member Data Documentation
std::string larcv::ImageClusterBase::_name private
name identifier, used to fetch configuration
Definition at line 82 of file ImageClusterBase.h.
Referenced by Name().
double larcv::ImageClusterBase::_proc_count private
algorithm execution counter (cumulative)
Definition at line 88 of file ImageClusterBase.h.
Referenced by AverageProcessTime(), and Process().
double larcv::ImageClusterBase::_proc_time private
algorithm execution time record (cumulative)
Definition at line 86 of file ImageClusterBase.h.
Referenced by AverageProcessTime(), and Process().
larcv::Watch larcv::ImageClusterBase::_watch private
algorithm profile stopwatch
Definition at line 84 of file ImageClusterBase.h.
Referenced by Process().
The documentation for this class was generated from the following files:
ImageClusterBase.h
ImageClusterBase.cxx