LArOpenCV: larcv::ImageClusterFactory Class Reference
larcv::ImageClusterFactory Class Reference
Factory class for instantiating algorithm instance by larcv::ImageClusterManager This factory class can instantiate a specified algorithm instance w/ provided instance name.
#include <ImageClusterFactory.h>
Public Member Functions
ImageClusterFactory ()
Default ctor, shouldn't be used.
~ImageClusterFactory ()
Default dtor.
void add_factory (const std::string name, larcv::ImageClusterFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
ImageClusterBase * create (const std::string name, const std::string instance_name)
Factory creation method (should be called by clients, possibly you!)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
Static Public Member Functions
static ImageClusterFactory & get ()
Static sharable instance getter.
Private Attributes
std::map< std::string,
larcv::ImageClusterFactoryBase * > _factory_map
Static factory container.
Static Private Attributes
static ImageClusterFactory * _me = nullptr
Static self.
Detailed Description
Factory class for instantiating algorithm instance by larcv::ImageClusterManager This factory class can instantiate a specified algorithm instance w/ provided instance name.
The actual factory core (to which each algorithm must register creation factory instance) is
a static std::map. Use static method to get a static instance (larcv::ImageClusterFactory::get)
to access a factory.
Definition at line 47 of file ImageClusterFactory.h.
Constructor & Destructor Documentation
larcv::ImageClusterFactory::ImageClusterFactory () inline
Default ctor, shouldn't be used.
Definition at line 51 of file ImageClusterFactory.h.
References LARCV_WARNING.
Referenced by get().
                           : laropencv_base("ImageClusterFactory")
     {LARCV_WARNING((*this)) << "To have a factory access static object via ImageClusterFactory::get()!" << std::endl;}
larcv::ImageClusterFactory::~ImageClusterFactory () inline
Default dtor.
Definition at line 54 of file ImageClusterFactory.h.
References _factory_map.
 {_factory_map.clear();}
Member Function Documentation
void larcv::ImageClusterFactory::add_factory (const std::string name, larcv::ImageClusterFactoryBase * factory) inline
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 59 of file ImageClusterFactory.h.
References _factory_map.
Referenced by larcv::EmptyImageClusterFactory::EmptyImageClusterFactory(), larcv::SBClusterFactory::SBClusterFactory(), and larcv::ToyImageClusterFactory::ToyImageClusterFactory().
     { _factory_map[name] = factory; }
ImageClusterBase* larcv::ImageClusterFactory::create (const std::string name, const std::string instance_name) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 62 of file ImageClusterFactory.h.
References _factory_map, and LARCV_ERROR.
{
       auto iter = _factory_map.find(name);
       if(iter == _factory_map.end() || !((*iter).second)) {
     LARCV_ERROR((*this)) << "Found no registered class " << name << std::endl;
     return nullptr;
       }
       return (*iter).second->create(instance_name);
     }
static ImageClusterFactory& larcv::ImageClusterFactory::get () inline static
Static sharable instance getter.
Definition at line 56 of file ImageClusterFactory.h.
References _me, and ImageClusterFactory().
Referenced by larcv::ImageClusterManager::Configure(), larcv::EmptyImageClusterFactory::EmptyImageClusterFactory(), larcv::SBClusterFactory::SBClusterFactory(), and larcv::ToyImageClusterFactory::ToyImageClusterFactory().
     { if(!_me) _me = new ImageClusterFactory; return *_me; }
const larcv::logger& larcv::laropencv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterManager::Configure().
     { return *_logger; }
void larcv::laropencv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterBase::Configure(), and larcv::ImageClusterManager::Configure().
     { _logger->set(level); }
Member Data Documentation
std::map<std::string,larcv::ImageClusterFactoryBase*> larcv::ImageClusterFactory::_factory_map private
Static factory container.
Definition at line 72 of file ImageClusterFactory.h.
Referenced by add_factory(), create(), and ~ImageClusterFactory().
larcv::ImageClusterFactory * larcv::ImageClusterFactory::_me = nullptr static private
Static self.
Definition at line 74 of file ImageClusterFactory.h.
Referenced by get().
The documentation for this class was generated from the following files:
ImageClusterFactory.h
ImageClusterFactory.cxx