LArOpenCV: larcv::EmptyImageCluster Class Reference
larcv::EmptyImageCluster Class Reference
A simple clustering algorithm meant to serve for testing/example by Kazu.
#include <EmptyImageCluster.h>
Public Member Functions
EmptyImageCluster (const std::string name="EmptyImageCluster")
Default constructor.
~EmptyImageCluster ()
Default destructor.
const std::string & Name () const
Name accessor.
void Configure (const ::fcllite::PSet &pset)
Configuration method.
void Profile (bool doit=true)
Profile flag setter.
larcv::ContourArray_t Process (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
wrapper execution method: internally executes Process function (see there for details)
size_t ProcessCount () const
Process count.
double ProcessTime () const
Process time.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
Protected Member Functions
void _Configure_ (const ::fcllite::PSet &pset)
Configuration method.
larcv::ContourArray_t _Process_ (const larcv::ContourArray_t &clusters, const ::cv::Mat &img, larcv::ImageMeta &meta)
Process method.
Private Attributes
std::vector< double > _canny_params
Detailed Description
A simple clustering algorithm meant to serve for testing/example by Kazu.
Definition at line 24 of file EmptyImageCluster.h.
Constructor & Destructor Documentation
larcv::EmptyImageCluster::EmptyImageCluster (const std::string name = "EmptyImageCluster") inline
Default constructor.
Definition at line 29 of file EmptyImageCluster.h.
                                                                 : ImageClusterBase(name)
     {}
larcv::EmptyImageCluster::~EmptyImageCluster () inline
Default destructor.
Definition at line 33 of file EmptyImageCluster.h.
 {}
Member Function Documentation
void larcv::EmptyImageCluster::_Configure_ (const ::fcllite::PSet & pset) protected virtual
Configuration method.
Implements larcv::ImageClusterBase.
Definition at line 7 of file EmptyImageCluster.cxx.
   {}
ContourArray_t larcv::EmptyImageCluster::_Process_ (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) protected virtual
Process method.
Implements larcv::ImageClusterBase.
Definition at line 10 of file EmptyImageCluster.cxx.
   { return ContourArray_t(); }
void larcv::ImageClusterBase::Configure (const ::fcllite::PSet & pset) inherited
Configuration method.
Definition at line 16 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_Configure_(), larcv::ImageClusterBase::_profile, LARCV_DEBUG, and larcv::laropencv_base::set_verbosity().
{
     LARCV_DEBUG((*this)) << "start" << std::endl;
     this->set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",(unsigned short)(this->logger().level()))));
     _profile = cfg.get<bool>("Profile",_profile);
     this->_Configure_(cfg);
     LARCV_DEBUG((*this)) << "end" << std::endl;
   }
const larcv::logger& larcv::laropencv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterManager::Configure().
     { return *_logger; }
const std::string& larcv::ImageClusterBase::Name () const inline inherited
Name accessor.
Definition at line 54 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_name.
 { return _name; };
ContourArray_t larcv::ImageClusterBase::Process (const larcv::ContourArray_t & clusters, const ::cv::Mat & img, larcv::ImageMeta & meta) inherited
wrapper execution method: internally executes Process function (see there for details)
Definition at line 27 of file ImageClusterBase.cxx.
References larcv::ImageClusterBase::_proc_count, larcv::ImageClusterBase::_proc_time, larcv::ImageClusterBase::_Process_(), larcv::ImageClusterBase::_profile, larcv::ImageClusterBase::_watch, larcv::Watch::Start(), and larcv::Watch::WallTime().
   {
     if(!_profile) return this->_Process_(clusters,img,meta);
     _watch.Start();
     auto result = this->_Process_(clusters,img,meta);
     _proc_time += _watch.WallTime();
     ++_proc_count;
     return result;
   }
size_t larcv::ImageClusterBase::ProcessCount () const inline inherited
Process count.
Definition at line 70 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_count.
 { return _proc_count; }
double larcv::ImageClusterBase::ProcessTime () const inline inherited
Process time.
Definition at line 72 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_proc_time.
 { return _proc_time; }
void larcv::ImageClusterBase::Profile (bool doit = true) inline inherited
Profile flag setter.
Definition at line 60 of file ImageClusterBase.h.
References larcv::ImageClusterBase::_profile.
 { _profile = doit; }
void larcv::laropencv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file laropencv_base.h.
References larcv::laropencv_base::_logger.
Referenced by larcv::ImageClusterBase::Configure(), and larcv::ImageClusterManager::Configure().
     { _logger->set(level); }
Member Data Documentation
std::vector<double> larcv::EmptyImageCluster::_canny_params private
Definition at line 47 of file EmptyImageCluster.h.
The documentation for this class was generated from the following files:
EmptyImageCluster.h
EmptyImageCluster.cxx