LArOpenCV: larlite::LArImageClusterBase Class Reference
larlite::LArImageClusterBase Class Reference abstract
User custom analysis class made by SHELL_USER_NAME.
#include <LArImageClusterBase.h>
Public Member Functions
LArImageClusterBase (const std::string name="LArImageClusterBase")
Default constructor.
virtual ~LArImageClusterBase ()
Default destructor.
bool initialize ()
IMPLEMENT in LArImageClusterBase.cc! Initialization method to be called before the analysis event loop.
bool analyze (storage_manager *storage)
IMPLEMENT in LArImageClusterBase.cc! Analyze a data event-by-event.
bool finalize ()
IMPLEMENT in LArImageClusterBase.cc! Finalize method to be called after all events processed.
larcv::ImageClusterManager & algo_manager (size_t plane_id)
const std::vector
< larcv::ImageClusterManager > & algo_manager_set () const
const std::string & producer () const
void set_config (const std::string cfg_file)
Protected Member Functions
virtual void _Report_ () const =0
virtual void _Configure_ (const ::fcllite::PSet &)=0
virtual void store_clusters (storage_manager *storage)=0
virtual void extract_image (storage_manager *storage)=0
Protected Attributes
::larcv::ImageManager _img_mgr
Private Member Functions
void Report () const
Private Attributes
std::vector
< larcv::ImageClusterManager > _alg_mgr_v
::larcv::ImageManager _orig_img_mgr
bool _store_original_img
std::string _producer
bool _profile
std::string _config_file
double _process_count
double _process_time_image_extraction
double _process_time_analyze
double _process_time_cluster_storage
Detailed Description
User custom analysis class made by SHELL_USER_NAME.
Definition at line 28 of file LArImageClusterBase.h.
Constructor & Destructor Documentation
larlite::LArImageClusterBase::LArImageClusterBase (const std::string name = "LArImageClusterBase")
Default constructor.
Definition at line 9 of file LArImageClusterBase.cxx.
References _alg_mgr_v, _producer, and _store_original_img.
                                                                : ana_base()
   {
     _name=name;
     _fout=0;
     _producer="";
     _alg_mgr_v.resize( ::larutil::Geometry::GetME()->Nplanes() );
     _store_original_img=false;
   }
virtual larlite::LArImageClusterBase::~LArImageClusterBase () inline virtual
Default destructor.
Definition at line 36 of file LArImageClusterBase.h.
 {}
Member Function Documentation
virtual void larlite::LArImageClusterBase::_Configure_ (const ::fcllite::PSet &) protected pure virtual
Implemented in larlite::LArImageHit, and larlite::LArImageWire.
Referenced by initialize().
virtual void larlite::LArImageClusterBase::_Report_ () const protected pure virtual
Implemented in larlite::LArImageHit, and larlite::LArImageWire.
Referenced by Report().
larcv::ImageClusterManager & larlite::LArImageClusterBase::algo_manager (size_t plane_id)
Definition at line 21 of file LArImageClusterBase.cxx.
References _alg_mgr_v.
   {
     if(plane_id >= _alg_mgr_v.size()) throw ::larcv::larbys("ImageClusterManager not found (invalid plane ID)!");
     return _alg_mgr_v[plane_id];
   }
const std::vector< larcv::ImageClusterManager > & larlite::LArImageClusterBase::algo_manager_set () const
Definition at line 18 of file LArImageClusterBase.cxx.
References _alg_mgr_v.
Referenced by larlite::LArImageHit::store_clusters().
   { return _alg_mgr_v; }
bool larlite::LArImageClusterBase::analyze (storage_manager * storage)
IMPLEMENT in LArImageClusterBase.cc! Analyze a data event-by-event.
Definition at line 52 of file LArImageClusterBase.cxx.
References _alg_mgr_v, _img_mgr, _orig_img_mgr, _process_count, _process_time_analyze, _process_time_cluster_storage, _process_time_image_extraction, _store_original_img, larcv::ImageManager::clear(), extract_image(), larcv::ImageManager::img_at(), larcv::ImageManager::meta_at(), larcv::ImageManager::push_back(), larcv::ImageManager::size(), larcv::Watch::Start(), store_clusters(), and larcv::Watch::WallTime().
{
     _img_mgr.clear();
     _orig_img_mgr.clear();
     ::larcv::Watch watch_all, watch_one;
     watch_all.Start();
     watch_one.Start();
     this->extract_image(storage);
     _process_time_image_extraction += watch_one.WallTime();
     if(_store_original_img) {
       for(size_t plane=0; plane<_img_mgr.size(); ++plane) {
     ::cv::Mat img;
     _img_mgr.img_at(plane).copyTo(img);
     _orig_img_mgr.push_back(img,_img_mgr.meta_at(plane));
       }
     }
     if(_img_mgr.size() != _alg_mgr_v.size()) throw ::larcv::larbys("# of imaged created != # of planes!");
     for(size_t plane = 0; plane < _alg_mgr_v.size(); ++plane) {
       auto& alg_mgr = _alg_mgr_v[plane];
       auto const& img = _img_mgr.img_at(plane);
       auto const& meta = _img_mgr.meta_at(plane);
       if(!meta.num_pixel_row() || !meta.num_pixel_column()) continue;
       alg_mgr.Process(img,meta);
     }
     watch_one.Start();
     this->store_clusters(storage);
     _process_time_cluster_storage += watch_one.WallTime();
     _process_time_analyze += watch_all.WallTime();
     ++_process_count;
     return true;
   }
virtual void larlite::LArImageClusterBase::extract_image (storage_manager * storage) protected pure virtual
Implemented in larlite::LArImageHit, and larlite::LArImageWire.
Referenced by analyze().
bool larlite::LArImageClusterBase::finalize ()
IMPLEMENT in LArImageClusterBase.cc! Finalize method to be called after all events processed.
Definition at line 113 of file LArImageClusterBase.cxx.
References _alg_mgr_v, and Report().
{
     Report();
     for(size_t plane=0; plane < _alg_mgr_v.size(); ++plane) {
       std::cout << "  \033[95mImageClusterManager\033[00m @ Plane " << plane << std::endl;
       _alg_mgr_v[plane].Report();
       std::cout << std::endl;
     }
     return true;
   }
bool larlite::LArImageClusterBase::initialize ()
IMPLEMENT in LArImageClusterBase.cc! Initialization method to be called before the analysis event loop.
Definition at line 27 of file LArImageClusterBase.cxx.
References _alg_mgr_v, _config_file, _Configure_(), _process_count, _process_time_analyze, _process_time_cluster_storage, _process_time_image_extraction, _producer, _profile, and _store_original_img.
{
     ::fcllite::ConfigManager cfg_mgr(_name);
     cfg_mgr.AddCfgFile(_config_file);
     auto const& main_cfg = cfg_mgr.Config().get_pset(_name);
     _profile = main_cfg.get<bool>("Profile");
     _producer = main_cfg.get<std::string>("Producer");
     _store_original_img = main_cfg.get<bool>("StoreOriginalImage");
     _process_count = 0;
     _process_time_image_extraction = 0;
     _process_time_analyze = 0;
     _process_time_cluster_storage = 0;
     this->_Configure_(main_cfg);
     if(_producer.empty()) throw ::larcv::larbys("No producer specified...");
     for(auto& mgr : _alg_mgr_v) mgr.Configure(cfg_mgr.Config().get_pset(mgr.Name()));
     return true;
   }
const std::string& larlite::LArImageClusterBase::producer () const inline
Definition at line 58 of file LArImageClusterBase.h.
References _producer.
Referenced by larlite::LArImageWire::extract_image(), larlite::LArImageHit::extract_image(), and larlite::LArImageHit::store_clusters().
 { return _producer; }
void larlite::LArImageClusterBase::Report () const private
Definition at line 95 of file LArImageClusterBase.cxx.
References _process_count, _process_time_analyze, _process_time_cluster_storage, _process_time_image_extraction, _profile, and _Report_().
Referenced by finalize().
{
     if(_profile) {
       std::cout << std::endl
         << "  =================== " << _name << " (analysis unit) Time Report ======================" << std::endl
         << "  # analyze() call ........ " << _process_count << std::endl
         << "  \033[95mAnalyze time\033[00m ............ Total " << _process_time_analyze
         << " [s] ... Average " << _process_time_analyze / _process_count << " [s]" << std::endl
         << "  \033[95mImage extraction time\033[00m ... Total " << _process_time_image_extraction
         << " [s] ... Average " << _process_time_image_extraction / _process_count << " [s]" << std::endl
         << "  \033[95mCluster storage time\033[00m .... Total " << _process_time_cluster_storage
         << " [s] ... Average " << _process_time_cluster_storage / _process_count << " [s]" << std::endl
         << std::endl;
       this->_Report_();
       std::cout << std::endl;
     }
   }
void larlite::LArImageClusterBase::set_config (const std::string cfg_file) inline
Definition at line 60 of file LArImageClusterBase.h.
References _config_file.
 {_config_file=cfg_file;}
virtual void larlite::LArImageClusterBase::store_clusters (storage_manager * storage) protected pure virtual
Implemented in larlite::LArImageHit, and larlite::LArImageWire.
Referenced by analyze().
Member Data Documentation
std::vector<larcv::ImageClusterManager> larlite::LArImageClusterBase::_alg_mgr_v private
Definition at line 63 of file LArImageClusterBase.h.
Referenced by algo_manager(), algo_manager_set(), analyze(), finalize(), initialize(), and LArImageClusterBase().
std::string larlite::LArImageClusterBase::_config_file private
Definition at line 68 of file LArImageClusterBase.h.
Referenced by initialize(), and set_config().
::larcv::ImageManager larlite::LArImageClusterBase::_img_mgr protected
Definition at line 79 of file LArImageClusterBase.h.
Referenced by analyze(), larlite::LArImageWire::extract_image(), and larlite::LArImageHit::extract_image().
::larcv::ImageManager larlite::LArImageClusterBase::_orig_img_mgr private
Definition at line 64 of file LArImageClusterBase.h.
Referenced by analyze().
double larlite::LArImageClusterBase::_process_count private
Definition at line 69 of file LArImageClusterBase.h.
Referenced by analyze(), initialize(), and Report().
double larlite::LArImageClusterBase::_process_time_analyze private
Definition at line 71 of file LArImageClusterBase.h.
Referenced by analyze(), initialize(), and Report().
double larlite::LArImageClusterBase::_process_time_cluster_storage private
Definition at line 72 of file LArImageClusterBase.h.
Referenced by analyze(), initialize(), and Report().
double larlite::LArImageClusterBase::_process_time_image_extraction private
Definition at line 70 of file LArImageClusterBase.h.
Referenced by analyze(), initialize(), and Report().
std::string larlite::LArImageClusterBase::_producer private
Definition at line 66 of file LArImageClusterBase.h.
Referenced by initialize(), LArImageClusterBase(), and producer().
bool larlite::LArImageClusterBase::_profile private
Definition at line 67 of file LArImageClusterBase.h.
Referenced by initialize(), and Report().
bool larlite::LArImageClusterBase::_store_original_img private
Definition at line 65 of file LArImageClusterBase.h.
Referenced by analyze(), initialize(), and LArImageClusterBase().
The documentation for this class was generated from the following files:
LArImageClusterBase.h
LArImageClusterBase.cxx