LArOpenCV: larcv::convert Namespace Reference
larcv::convert Namespace Reference
C++ namespace for a collection of Python<=>LArOpenCV C++ object conversion functions/classes.
Classes
class PyAllowThreads
class PyEnsureGIL
class NumpyAllocator
class NDArrayConverter
Enumerations
enum { ARG_NONE = 0, ARG_MAT = 1, ARG_SCALAR = 2 }
Functions
static int failmsg (const char *fmt,...)
static int failmsg (const char *fmt,...)
static PyObject * pyObjectFromRefcount (const int *refcount)
static int * refcountFromPyObject (const PyObject *obj)
Variables
NumpyAllocator g_numpyAllocator
static size_t REFCOUNT_OFFSET
Detailed Description
C++ namespace for a collection of Python<=>LArOpenCV C++ object conversion functions/classes.
Enumeration Type Documentation
anonymous enum
Enumerator
ARG_NONE
ARG_MAT
ARG_SCALAR
Definition at line 63 of file NDArrayConverter.h.
 { ARG_NONE = 0, ARG_MAT = 1, ARG_SCALAR = 2 };
Function Documentation
static int larcv::convert::failmsg (const char * fmt, ...) static
Definition at line 24 of file NDArrayConverter.cxx.
Referenced by larcv::convert::NDArrayConverter::toMat().
     {
       char str[1000];
       va_list ap;
       va_start(ap, fmt);
       vsnprintf(str, sizeof(str), fmt, ap);
       va_end(ap);
       PyErr_SetString(PyExc_TypeError, str);
       return 0;
     }
static int larcv::convert::failmsg (const char * fmt, ...) static
static PyObject* larcv::convert::pyObjectFromRefcount (const int * refcount) inline static
Definition at line 50 of file NDArrayConverter.h.
References REFCOUNT_OFFSET.
Referenced by larcv::convert::NDArrayConverter::toNDArray().
     {
       return (PyObject*)((size_t)refcount - REFCOUNT_OFFSET);
     }
static int* larcv::convert::refcountFromPyObject (const PyObject * obj) inline static
Definition at line 55 of file NDArrayConverter.h.
References REFCOUNT_OFFSET.
Referenced by larcv::convert::NDArrayConverter::toMat().
     {
       return (int*)((size_t)obj + REFCOUNT_OFFSET);
     }
Variable Documentation
NumpyAllocator larcv::convert::g_numpyAllocator
Definition at line 198 of file NDArrayConverter.cxx.
Referenced by larcv::convert::NDArrayConverter::toMat(), and larcv::convert::NDArrayConverter::toNDArray().
size_t larcv::convert::REFCOUNT_OFFSET static
Initial value:
= (size_t)&(((PyObject*)0)->ob_refcnt) +
      (0x12345678 != *(const size_t*)"\x78\x56\x34\x12\0\0\0\0\0")*sizeof(int)
Definition at line 47 of file NDArrayConverter.h.
Referenced by pyObjectFromRefcount(), and refcountFromPyObject().