LArOpenCV: larcv Namespace Reference
larcv Namespace Reference
LArCaffe | Core | ImageCluster | Utils
C++ namespace for developping LArTPC software interface to OpenCV based algorithm tools (LArOpenCV)
Namespaces
convert
C++ namespace for a collection of Python<=>LArOpenCV C++ object conversion functions/classes.
msg
Namespace for larcv message related types.
Classes
class ImageManager
A utility container class for multiple image objects with corresponding metadata per image.
class laropencv_base
Very base class of all everything else defined in this framework.
class Point2DArray
An array of 2D points implemented as 1D std::vector<double> for I/O performance It is meant to be used to store larcv::Contour_t in a ROOT file but not yet implemented (ignore!)
class EmptyImageCluster
A simple clustering algorithm meant to serve for testing/example by Kazu.
class EmptyImageClusterFactory
A concrete factory class for larcv::EmptyImageCluster.
class ImageClusterBase
An abstract base class for ImageCluster algorithms.
class ImageClusterFactoryBase
Abstract base class for factory (to be implemented per algorithm)
class ImageClusterFactory
Factory class for instantiating algorithm instance by larcv::ImageClusterManager This factory class can instantiate a specified algorithm instance w/ provided instance name.
class ImageClusterManager
Class to execute a chain of algorithms to a given image input.
class SBCluster
class SBClusterFactory
A concrete factory class for larcv::SBCluster.
class ToyImageCluster
A simple clustering algorithm meant to serve for testing/example by Kazu.
class ToyImageClusterFactory
A concrete factory class for larcv::ToyImageCluster.
class Watch
a very simple stopwatch class for simple time measurement
class Image2D
Borrowed from larcaffe (see larcaffe::Image2D)
class ImageMeta
Borrowed from larcaffe (see larcaffe::ImageMeta)
class larbys
Borrowed from larcaffe (see larcaffe::larbys)
Typedefs
typedef ::larcaffe::Image2D Image2D
typedef ::larcaffe::ImageMeta ImageMeta
typedef ::larcaffe::larbys larbys
typedef ::larcaffe::Point2D Point2D
Stolen from larcaffe.
typedef ::larcaffe::logger logger
typedef size_t AlgorithmID_t
larcv::ImageClusterBase inherit algorithm's unique identifier within larcv::ClusterImageManager
typedef size_t ClusterID_t
A cluster's unique identifier within larcv::ClusterImageManager.
typedef std::vector< cv::Point > Contour_t
A 2D contour type.
typedef std::vector
< larcv::Contour_t > ContourArray_t
A set of 2D contours.
Functions
::cv::Rect BoundingBox (const larcv::Contour_t &cluster)
::cv::Mat CreateSubMatRef (const larcv::Contour_t &cluster, cv::Mat &img)
::cv::Mat CreateSubMatCopy (const larcv::Contour_t &cluster, const cv::Mat &img)
Variables
static const size_t kINVALID_SIZE = std::numeric_limits<size_t>::max()
Used as an invalid value identifier for size_t.
static const int kINVALID_INT = std::numeric_limits<int>::max()
Used as an invalid value identifier for int.
static EmptyImageClusterFactory __global_EmptyImageClusterFactory__
Global larcv::EmptyImageClusterFactory to register ImageClusterFactory.
static const size_t kINVALID_ID = larcv::kINVALID_SIZE
A constant to signify invalid "id" in general.
static const AlgorithmID_t kINVALID_ALGO_ID = kINVALID_ID
A constant to signify, in particular, an invalid larcv::AlgorithmID_t.
static const ClusterID_t kINVALID_CLUSTER_ID = kINVALID_ID
A constant to signify, in particular, an invalid larcv::ClusterID_t.
static SBClusterFactory __global_SBClusterFactory__
Global larcv::SBClusterFactory to register ImageClusterFactory.
static ToyImageClusterFactory __global_ToyImageClusterFactory__
Global larcv::ToyImageClusterFactory to register ImageClusterFactory.
Detailed Description
C++ namespace for developping LArTPC software interface to OpenCV based algorithm tools (LArOpenCV)
Typedef Documentation
typedef size_t larcv::AlgorithmID_t
larcv::ImageClusterBase inherit algorithm's unique identifier within larcv::ClusterImageManager
Definition at line 10 of file ImageClusterTypes.h.
typedef size_t larcv::ClusterID_t
A cluster's unique identifier within larcv::ClusterImageManager.
Definition at line 12 of file ImageClusterTypes.h.
typedef std::vector<cv::Point> larcv::Contour_t
A 2D contour type.
Definition at line 14 of file ImageClusterTypes.h.
typedef std::vector<larcv::Contour_t> larcv::ContourArray_t
A set of 2D contours.
Definition at line 16 of file ImageClusterTypes.h.
typedef ::larcaffe::Image2D larcv::Image2D
Definition at line 68 of file Image2D.h.
typedef ::larcaffe::ImageMeta larcv::ImageMeta
Definition at line 103 of file ImageMeta.h.
typedef ::larcaffe::larbys larcv::larbys
Definition at line 52 of file larbys.h.
typedef ::larcaffe::logger larcv::logger
Definition at line 24 of file laropencv_logger.h.
typedef ::larcaffe::Point2D larcv::Point2D
Stolen from larcaffe.
Definition at line 37 of file LArCVTypes.h.
Function Documentation
cv::Rect larcv::BoundingBox (const larcv::Contour_t & cluster)
Definition at line 10 of file Utilities.cxx.
Referenced by CreateSubMatCopy(), and CreateSubMatRef().
   {
     if(cluster.size()<2)
       throw larbys("Cannot create SubMatrix for a contour of size < 2!");
     int x_min = INT_MAX;
     int y_min = INT_MAX;
     int x_max = 0;
     int y_max = 0;
     for(auto const& pt : cluster) {
       if(pt.x < x_min) x_min = pt.x;
       if(pt.x > x_max) x_max = pt.x;
       if(pt.y < y_min) y_min = pt.y;
       if(pt.y > y_max) y_max = pt.y;
     }
     return ::cv::Rect( x_min, y_min,
                x_max - x_min + 1,
                y_max - y_min + 1);
   }
cv::Mat larcv::CreateSubMatCopy (const larcv::Contour_t & cluster, const cv::Mat & img)
Definition at line 47 of file Utilities.cxx.
References BoundingBox().
   {
     if(cluster.size()<2)
       throw larbys("Cannot create SubMatrix for a contour of size < 2!");
     auto bbox = BoundingBox(cluster);
     ::cv::Mat result = ::cv::Mat::zeros(img.size(),img.type());
     for(int x=0; x<img.rows; ++x) {
       for(int y=0; y<img.cols; ++y) {
     int submat_x = x - bbox.x;
     int submat_y = y - bbox.y;
     double inside = ::cv::pointPolygonTest(cluster,::cv::Point2f(x,y),false);
     if(inside<0) continue;
     result.at<float>(submat_x,submat_y,0) = img.at<float>(x,y,0);
       }
     }
     return result;
   }
cv::Mat larcv::CreateSubMatRef (const larcv::Contour_t & cluster, cv::Mat & img)
Definition at line 34 of file Utilities.cxx.
References BoundingBox().
   {
     if(cluster.size()<2)
       throw larbys("Cannot create SubMatrix for a contour of size < 2!");
     auto bbox = BoundingBox(cluster);
     ::cv::Mat result;
     img(bbox).copyTo(result);
     return result;
   }
Variable Documentation
EmptyImageClusterFactory larcv::__global_EmptyImageClusterFactory__ static
Global larcv::EmptyImageClusterFactory to register ImageClusterFactory.
Definition at line 65 of file EmptyImageCluster.h.
SBClusterFactory larcv::__global_SBClusterFactory__ static
Global larcv::SBClusterFactory to register ImageClusterFactory.
Definition at line 60 of file SBCluster.h.
ToyImageClusterFactory larcv::__global_ToyImageClusterFactory__ static
Global larcv::ToyImageClusterFactory to register ImageClusterFactory.
Definition at line 65 of file ToyImageCluster.h.
const AlgorithmID_t larcv::kINVALID_ALGO_ID = kINVALID_ID static
A constant to signify, in particular, an invalid larcv::AlgorithmID_t.
Definition at line 20 of file ImageClusterTypes.h.
Referenced by larcv::ImageClusterManager::ClusterID(), larcv::ImageClusterManager::Clusters(), and larcv::ImageClusterManager::GetAlgID().
const ClusterID_t larcv::kINVALID_CLUSTER_ID = kINVALID_ID static
A constant to signify, in particular, an invalid larcv::ClusterID_t.
Definition at line 22 of file ImageClusterTypes.h.
Referenced by larcv::ImageClusterManager::ClusterID(), and larlite::LArImageHit::store_clusters().
const size_t larcv::kINVALID_ID = larcv::kINVALID_SIZE static
A constant to signify invalid "id" in general.
Definition at line 18 of file ImageClusterTypes.h.
const int larcv::kINVALID_INT = std::numeric_limits<int>::max() static
Used as an invalid value identifier for int.
Definition at line 35 of file LArCVTypes.h.
const size_t larcv::kINVALID_SIZE = std::numeric_limits<size_t>::max() static
Used as an invalid value identifier for size_t.
Definition at line 33 of file LArCVTypes.h.